<a href="https://colab.research.google.com/github/leehuichann/Algorithm/blob/main/6%EC%A3%BC%EC%B0%A8%EA%B3%BC%EC%A0%9C_202315167.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**실습 3**

In [ ]:
import numpy as np

# 원래 행렬
A = np.array([
    [1, 2, 3],
    [2, 5, 3],
    [1, 0, 8]
], dtype = float)

# (i, j)번째 행과 열을 제거한 소행렬
def get_minor(matrix, row, col) :
  return np.delete(
      np.delete(matrix, row, axis = 0),
      col,
      axis = 1
  )

# 여인수행렬 계산
def cofactor_matrix(matrix) :
  n = matrix.shape[0]
  C = np.zeros((n,n))
  for i in range(n) :
    for j in range(n) :
      minor = get_minor(matrix, i, j)
      C[i, j] = ((-1) ** (i + j)) * np.linalg.det(minor)

  return C

# 행렬식 계산
det_A = round(np.linalg.det(A))

if det_A == 0 :
  print("행렬식이 0이므로 역행렬이 존재하지 않습니다.")
else :
  # 1. 여인수행렬
  C = cofactor_matrix(A)
  # 2. 수반행렬 = 여인수행렬의 전치행렬
  adj_A = C.T
  # 3. 역행렬
  inverse_A = (1 / det_A) * adj_A
  # 부동소수점 오차 정리
  C = np.round(C, 10)
  adj_A = np.round(adj_A, 10)
  inverse_A = np.round(inverse_A, 10)

  print("행렬 A")
  print(A)
  print("\n행렬식 det(A)")
  print(det_A)
  print("\n여인수행렬 C")
  print(C)
  print("\n수반행렬 adj(A)")
  print(adj_A)
  print("\n역행렬 A^(-1)")
  print(inverse_A)
  print("\n검산 A x A^(-1)")
  print(np.round(A @ inverse_A, 10))


행렬 A
[[1. 2. 3.]
 [2. 5. 3.]
 [1. 0. 8.]]

행렬식 det(A)
-1

여인수행렬 C
[[ 40. -13.  -5.]
 [-16.   5.   2.]
 [ -9.   3.   1.]]

수반행렬 adj(A)
[[ 40. -16.  -9.]
 [-13.   5.   3.]
 [ -5.   2.   1.]]

역행렬 A^(-1)
[[-40.  16.   9.]
 [ 13.  -5.  -3.]
 [  5.  -2.  -1.]]

검산 A x A^(-1)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**실습 4**

In [ ]:
import numpy as np
np.set_printoptions(suppress=True, precision=2)

# 계수행렬 A
A = np.array([
    [1, 2, 3],
    [1, 3, 6],
    [2, 6, 13]
], dtype=float)

# 상수벡터 b
b = np.array([
    [1],
    [3],
    [5]
], dtype=float)

print("계수행렬 A")
print(A)
print("\n상수벡터 b")
print(b)

# 행렬식 계산
det_A = np.linalg.det(A)
print("\n행렬식 det(A)")
print(round(det_A, 10))

# 역행렬 존재 여부 확인
if np.isclose(det_A, 0) :
  print("\ndet(A) = 0 이므로 역행렬이 존재하지 않습니다.")
else :
  # A의 역행렬
  A_inverse = np.linalg.inv(A)

  print("\nA의 역행렬")
  print(A_inverse)
  # X = A^(-1)b
  X = A_inverse @ b
  print("\n선형시스템의 해")
  print(X)

  x, y, z = X.flatten()
  print(f"\nx = {x:0f}")
  print(f"y = {y:0f}")
  print(f"z = {z:0f}")

  # 검산
  print("\n검산 결과 A @ X")
  print(A @ X)

계수행렬 A
[[ 1.  2.  3.]
 [ 1.  3.  6.]
 [ 2.  6. 13.]]

상수벡터 b
[[1.]
 [3.]
 [5.]]

행렬식 det(A)
1.0

A의 역행렬
[[ 3. -8.  3.]
 [-1.  7. -3.]
 [-0. -2.  1.]]

선형시스템의 해
[[-6.]
 [ 5.]
 [-1.]]

x = -6.000000
y = 5.000000
z = -1.000000

검산 결과 A @ X
[[1.]
 [3.]
 [5.]]
